module compiler

import datatypes

pub struct Scanner {
pub mut:
	absolute_file_path string // The absolute path of the file
	text               string // The whole text of the file
	pos                int    // The current position in the text
	line               int    // The current line in the text

	messages datatypes.Set[Message] = datatypes.Set[Message]{} // The messages generated by the scanner. They are not sorted.	
}
